### ISSUE TITLE
Invalid arguments error for path

### ISSUE THREAD

**Issue by ts10net** [richinfante/richinfante.com#1]
**Page the issue appears on:**
  > [richinfante.com/2017/12/5/reverse-engineering-the-ios-backup-part-two](https://www.richinfante.com/2017/12/5/reverse-engineering-the-ios-backup-part-two)

  **Description:**
  > What did I mess up?
  I get the below error when I give the command

`internal/validators.js:112
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
    at validateString (internal/validators.js:112:11)
    at Object.join (path.js:375:7)`

**Comment by richinfante** [comment]
Can you provide more context so I can try to reproduce the issue - Is there a specific command listed on this page that causes this error to be thrown?

**Comment by richinfante** [comment]
_closing as inactive_
