### ISSUE TITLE
New update IOS  encrypted backup file.

### ISSUE THREAD

**Issue by ssuriyayuvan** [richinfante/richinfante.com#2]
**Page the issue appears on:**
  > [richinfante.com/2017/3/16/reverse-engineering-the-ios-backup](https://www.richinfante.com/2017/3/16/reverse-engineering-the-ios-backup)

  **Description:**
I need to decrypt that backupfile which was encrypt after v13. Need solution asap

**Comment by richinfante** [comment]
Hi - The current iteration of this tool doesn't support decrypting backups

I'd advise looking into alternative software for doing this if you're under a time constraint. I have a tool in the works featuring full decryption functionality but it will likely will not be complete for several months
