### ISSUE TITLE
Some extra things you might consider...

### ISSUE THREAD

**Issue by steverpalmer** [richinfante/richinfante.com#3]
**Page the issue appears on:**
  > [richinfante.com/2019/01/27/raspberry-pi-setup](https://www.richinfante.com/2019/01/27/raspberry-pi-setup)

  **Description:**
Thanks for this.  I'm just starting my own checklist and it is good to cross reference against others.  No mess-up, just some other things you might want to consider:
* using `etckeeper` to keep track of changes in `\etc`
* modifying `/etc/systemd/timesyncd.conf` to refer to national time servers
* increasing the size of the swap space (dphys-swapfile).  (I know there are many arguments over swap space on SD cards, but I'd hate to run out of memory on a principle.)

**Comment by richinfante** [comment]
Thanks for this - if I revisit my pi setup checklist, I'll consider some of these
