### ISSUE TITLE
The code of errors is not determined by their declaration order

### ISSUE THREAD

**Issue by dirtyhenry** [richinfante/richinfante.com#4]
**Page the issue appears on:**
  > [richinfante.com/2018/01/25/demystifying-swift-errors](https://www.richinfante.com/2018/01/25/demystifying-swift-errors)

  **Description:**
  > What did I mess up?

I just realized that the following: 

```swift
enum MyError: Error {
  case errorZero
  case errorOne
}
```  

could result in `errorOne` having the code 0 and `errorZero` having the code 1.

So I was searching on the internet if we could be sure that, for a given source code, the attribution was at least deterministic when I stumbled upon your blog post. The section mentioning that the code above is equivalent to: 

```swift
enum MyError: Int, Error {
  case errorZero = 0
  case errorOne = 1
}
```

is false, as of Swift 5.3.

Thanks for the article though. It provides good tips. 🙏

**Comment by richinfante** [comment]
Closing out old issues, I had removed this long ago (it was mostly derived from observations and not actually documented stuff). Thank you!
