### ISSUE TITLE
I can't obtain video (Syma drone)

### ISSUE THREAD

**Issue by Muhammadyusuf96** [richinfante/richinfante.com#5]
**Page the issue appears on:**
  > [richinfante.com/2018/05/31/rooting-your-drone](https://www.richinfante.com/2018/05/31/rooting-your-drone)

  **Description:**
  > I'm about SYMA X5UW (720p)

We can't just obtain video by `get http://192.168.1.1/videostream.cgi?user=admin&pwd=`. It gives error: `The specified stream is not mjpeg coded`. Do you know what to do?
There some extra commands (SD card):

Get record
http://192.168.1.1/get_record.cgi?path=

Delete record
http://192.168.1.1/del_record.cgi?user=admin&pwd=&name=

Delete snapshot
http://192.168.1.1/del_snapshot.cgi?user=admin&pwd=&name=

**Comment by richinfante** [comment]
Hi there -  Unsure without looking at it, but your drone might not support it. It's entirely possible the stream is some other encoding that isn't supported buy the software you're using
