### ISSUE TITLE
Activity LED is alway off

### ISSUE THREAD

**Issue by cmonty14** [richinfante/richinfante.com#6]
**Page the issue appears on:**
  > [richinfante.com/2021/08/11/raspberry-pi-gpio-status-lights](https://www.richinfante.com/2021/08/11/raspberry-pi-gpio-status-lights)

  **Description:**
The setting for activity LED
`dtoverlay=act-led,gpio=21`
 is not working, means the LED is always off. 

Any idea what's causing this issue?

**Comment by richinfante** [comment]
Closing out some older issues - missed the notification on this one. but anyways:

Is it possible you've got the LED connected the physical pin labeled 21 and not the logical GPIO pin? if those are mixed up this would be sending voltage to the other pin
