### ISSUE TITLE
Micro typo in the join example

### ISSUE THREAD

**Issue by dmbarrad** [richinfante/richinfante.com#7]
**Page the issue appears on:**
    > [richinfante.com/2020/11/23/using-ed-the-unix-line-editor](https://www.richinfante.com/2020/11/23/using-ed-the-unix-line-editor)

    **Description:**
    > What did I mess up?
>    <range>? j - joins selected lines
>     Examples:
>        1,5d - joins the first 5 lines

correct is 1,5j

**Comment by richinfante** [comment]
thanks for this! Fixed.
