### ISSUE TITLE
v// example

### ISSUE THREAD

**Issue by kensanata** [richinfante/richinfante.com#8]
**Page the issue appears on:**
> [https://www.richinfante.com/2020/11/23/using-ed-the-unix-line-editor](https://www.richinfante.com/2020/11/23/using-ed-the-unix-line-editor)

**Description:**
I think this line is missing a "not". Or I'm not sure how to interpret this?

- `v/foo/` - selects lines containing the string “foo”

Perhaps this needs more words. What happens if the file has not-matching lines in two regions?

```
bar
foo
baz
```

It probably doesn't result in two selections. Is bar selected? baz? Does it depend on where the search starts?

**Comment by richinfante** [comment]
Yep, good catch there, will fix that!

It does indeed select all the lines not match, so in your example `v/b/p` would not print "bar" / "baz" and would only print "foo".

**Comment by richinfante** [comment]
fixed!
